# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Visual_Search' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  pod 'MRProgress'
  pod 'AFNetworking'
end
