source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
project 'Visual_Search.xcodeproj'
target 'Visual_Search' do
pod 'AFNetworking', '~> 3.0'
pod 'RETableViewManager'
pod 'MRProgress'
pod 'boost'
pod 'eigen'
end